add_newline = false

format = """
$username$hostname$directory$git_branch$time$cmd_duration
[└─](bold #73daca)$character"""

[username]
show_always = true
style_user = "bold #7aa2f7"
style_root = "bold #f7768e"
format = "[┌──\\(](bold #73daca)[$user]($style)"

[hostname]
ssh_only = false
style = "bold #7aa2f7"
format = "[@](bold #7aa2f7)[$hostname]($style)[\\)](bold #73daca)"

[directory]
style = "bold #c0caf5"
truncation_length = 5
truncation_symbol = ".../"
format = "[-\\[](bold #73daca)[$path]($style)[\\]](bold #73daca)"

[time]
disabled = false
format = " [\\[$time\\]](#73daca)"
time_format = "%d/%m %H:%M"

[git_branch]
style = "bold #dca561"
format = " [$symbol$branch]($style)"
symbol = ""

[git_status]
disabled = true

[python]
style = "bold #dca561"
format = " [py:$version]($style)"

[cmd_duration]
min_time = 2_000
style = "bold #dca561"
format = " [$duration]($style)"

[character]
success_symbol = "[\\$](bold #7aa2f7)"
error_symbol = "[\\$](bold #f7768e)"
